# Generated by Django 2.1 on 2020-01-10 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='meeting_type',
            field=models.CharField(choices=[('술팟', '술팟'), ('게임팟', '게임팟'), ('운동팟', '운동팟'), ('기타', '기타')], default='술팟', max_length=10),
        ),
    ]
