# Generated by Django 2.1 on 2020-01-10 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20200110_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='join',
            name='postID',
            field=models.IntegerField(),
        ),
    ]
