# Generated by Django 2.1 on 2020-01-10 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20200110_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='join',
            name='postTime',
            field=models.DateField(default='2020-10-10'),
        ),
        migrations.AddField(
            model_name='join',
            name='postTitle',
            field=models.CharField(default='titme', max_length=50),
        ),
    ]
