# Generated by Django 2.1 on 2020-01-11 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20200110_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='count',
        ),
        migrations.AddField(
            model_name='join',
            name='post',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='post.Post'),
        ),
    ]
