# Generated by Django 2.1 on 2020-01-11 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_auto_20200111_0306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='join',
            name='post',
        ),
    ]
