# Generated by Django 2.1 on 2020-01-11 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_remove_join_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='join',
            name='postID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Post'),
        ),
    ]
