# Generated by Django 2.1 on 2020-01-11 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_auto_20200111_0311'),
    ]

    operations = [
        migrations.AddField(
            model_name='join',
            name='psot',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='post.Post'),
        ),
        migrations.AlterField(
            model_name='join',
            name='postID',
            field=models.IntegerField(),
        ),
    ]
