# Generated by Django 2.1 on 2020-01-11 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_auto_20200111_0317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='join',
            name='psot',
        ),
        migrations.AlterField(
            model_name='join',
            name='postTitle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Post'),
        ),
    ]
