# Generated by Django 2.1 on 2020-01-11 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_auto_20200111_0319'),
    ]

    operations = [
        migrations.AddField(
            model_name='join',
            name='post',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='post.Post'),
        ),
        migrations.AlterField(
            model_name='join',
            name='postTime',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='join',
            name='postTitle',
            field=models.CharField(max_length=50),
        ),
    ]
