# Generated by Django 2.1 on 2020-01-11 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_auto_20200111_0324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='join',
            name='postID',
            field=models.IntegerField(default=0),
        ),
    ]
