# Generated by Django 2.1 on 2020-01-11 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_auto_20200111_0327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='join',
            name='post',
        ),
        migrations.RemoveField(
            model_name='join',
            name='user',
        ),
        migrations.DeleteModel(
            name='Join',
        ),
    ]
