# Generated by Django 2.1 on 2020-01-13 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_auto_20200111_1056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='meeting_place',
            new_name='place',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='meeting_time',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='meeting_type',
            new_name='type_meet',
        ),
    ]
