# Generated by Django 2.1 on 2020-01-11 11:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0013_auto_20200111_1056'),
        ('main', '0003_join'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Join',
            new_name='Schedule',
        ),
    ]
