# Generated by Django 2.1 on 2020-01-11 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200111_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='postType',
            field=models.CharField(default='술팟', max_length=50),
        ),
    ]
