# Generated by Django 2.1 on 2020-01-13 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_schedule_posttype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='postTime',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='postTitle',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='postType',
        ),
    ]
